# Generated by Django 5.0 on 2024-04-12 21:09

import app_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('path', models.ImageField(upload_to=app_main.models.update_filename)),
            ],
        ),
    ]
